apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamart
  template:
    metadata:
      labels:
        app: datamart
    spec:
      serviceAccountName: spark
      containers:
      - name: datamart
        image: datamart-image
        imagePullPolicy: Never
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: datamart
spec:
  selector:
    app: datamart
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: datamart-driver
  labels:
    app: datamart
spec:
  clusterIP: None
  selector:
    app: datamart
  ports:
  - name: driver-rpc
    port: 33221
    targetPort: 33221