services:
  main:
    build: .
    image: main-image
    container_name: main-container
    networks:
    - app-network
    depends_on:
      mongodb:
        condition: service_healthy
      datamart:
        condition: service_healthy
    ports:
    - "4040:4040"

  datamart:
    build:
      context: .
      dockerfile: Dockerfile.datamart
    image: datamart-image
    container_name: datamart-container
    networks:
    - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
    - "8080:8080"
    - "4041:4041"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2400s
  
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - ./data/mongo-dump:/dump:ro
      - ./scripts/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
    networks:
      - app-network
    healthcheck:
      test: bash -c '[ -f /data/db/RESTORE_DONE ] && mongosh --quiet -u user -p 12345 --eval "db.adminCommand(\"ping\")"'
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
  
networks:
  app-network:
    driver: bridge
