apiVersion: batch/v1
kind: Job
metadata:
  name: main-job
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
      - name: main
        image: main-image
        command: ["python", "src/main.py"]
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "3"
      restartPolicy: Never