apiVersion: v1
kind: Service
metadata:
  name: main-driver
  labels:
    spark-role: driver
spec:
  clusterIP: None
  selector:
    spark-role: driver
  ports:
  - name: driver-rpc
    port: 7078
    targetPort: 7078
