apiVersion: batch/v1
kind: Job
metadata:
  name: main-job
spec:
  template:
    metadata:
      labels:
        spark-role: driver
        app: main
    spec:
      serviceAccountName: spark
      containers:
      - name: main
        image: main-image
        imagePullPolicy: Never
        command: ["python", "src/main.py"]
        ports:
        - containerPort: 7078
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: main-driver
  labels:
    spark-role: driver
spec:
  clusterIP: None
  selector:
    spark-role: driver
  ports:
  - name: driver-rpc
    port: 7078
    targetPort: 7078